version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      DATABASE_HOST: 172.21.0.2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.dev
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  app:
    build: .
    command: ["python", "main.py"]
    volumes:
      - .:/app
    links:
      - db
    